# Generated by Django 5.1.3 on 2024-11-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('customer_type', models.CharField(choices=[('เทศบาลเมือง', 'Municipality City'), ('เทศบาลตำบล', 'Municipality Town'), ('องค์กรบริหารส่วนตำบล', 'Subdistrict Administration Organization'), ('องค์การบริหารส่วนจังหวัด', 'Provincial Administration Organization')], default='เทศบาลเมือง', max_length=100)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], default='Active', max_length=10)),
            ],
        ),
    ]
