# Generated by Django 5.1.3 on 2024-11-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('เทศบาลเมือง', 'Municipality City'), ('เทศบาลตำบล', 'Municipality Town'), ('องค์กรบริหารส่วนตำบล', 'Subdistrict Administration Organization'), ('องค์การบริหารส่วนจังหวัด', 'Provincial Administration Organization')], max_length=100),
        ),
    ]
