# Generated by Django 5.1.3 on 2024-11-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_alter_customer_customer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('เทศบาลเมือง', 'เทศบาลเมือง'), ('เทศบาลตำบล', 'เทศบาลตําบล'), ('องค์กรบริหารส่วนตำบล', 'องค์กรบริหารส่วนตําบล'), ('องค์การบริหารส่วนจังหวัด', 'องค์การบริหารส่วนจังหวัด')], max_length=100),
        ),
    ]
