# Generated by Django 5.1.3 on 2024-12-03 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_address_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(choices=[('อำเภอเมืองกาญจนบุรี', 'อำเภอเมืองกาญจนบุรี'), ('อำเภอท่ามะกา', 'อำเภอท่ามะกา'), ('อำเภอท่าม่วง', 'อำเภอท่าม่วง'), ('อำเภอพนมทวน', 'อำเภอพนมทวน'), ('อำเภอเลาขวัญ', 'อำเภอเลาขวัญ'), ('อำเภอศรีสวัสดิ์', 'อำเภอศรีสวัสดิ์'), ('อำเภอไทรโยค', 'อำเภอไทรโยค')], max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='subdistrict',
            field=models.CharField(choices=[('ตำบลปากแพรก', 'ตำบลปากแพรก'), ('ตำบลดอนชะเอม', 'ตำบลดอนชะเอม'), ('ตำบลวังขนาย', 'ตำบลวังขนาย'), ('ตำบลทุ่งสมอ', 'ตำบลทุ่งสมอ'), ('ตำบลหนองปลิง', 'ตำบลหนองปลิง'), ('ตำบลนาสวน', 'ตำบลนาสวน'), ('ตำบลท่าเสา', 'ตำบลท่าเสา')], max_length=100),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=100, unique=True)),
                ('bill_type', models.CharField(choices=[('Invoice', 'Invoice'), ('Receipt', 'Receipt'), ('Credit Note', 'Credit Note'), ('Debit Note', 'Debit Note')], max_length=50)),
                ('bill_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.customer')),
            ],
        ),
    ]
